import { createElement } from 'lwc';
import LwcDynamicTable02092023 from 'c/lwcDynamicTable02092023';

describe('c-lwc-dynamic-table02092023', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-lwc-dynamic-table02092023', {
            is: LwcDynamicTable02092023
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});